apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurants-service
  labels:
    app: restaurants-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurants-service
  template:
    metadata:
      labels:
        app: restaurants-service
    spec:
      containers:
        - name: restaurants-service
          image: zayto/restaurants:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgres://zayto:zayto_password@postgres:5432/zayto_db"
          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 20

