apiVersion: v1
kind: Service
metadata:
  name: restaurants-service
  labels:
    app: restaurants-service
spec:
  selector:
    app: restaurants-service
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP

