apiVersion: v1
kind: Service
metadata:
  name: partner-service
  labels:
    app: partner-service
spec:
  type: ClusterIP
  selector:
    app: partner-service
  ports:
    - name: http
      port: 3005
      targetPort: 3005

