openapi: 3.0.3
info:
  title: Zayto API Gateway
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Healthy
  /api/restaurants:
    get:
      summary: Proxy to restaurants list
      responses:
        '200':
          description: OK
  /api/restaurants/{id}:
    get:
      summary: Proxy to restaurant by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /api/restaurants/{id}/menu:
    get:
      summary: Proxy to restaurant menu
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /api/restaurants/{id}/reviews:
    get:
      summary: Proxy to restaurant reviews
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK


