openapi: 3.0.3
info:
  title: Restaurants Service API
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Healthy
  /restaurants:
    get:
      summary: List restaurants
      parameters:
        - in: query
          name: cuisine_type
          schema:
            type: string
        - in: query
          name: search
          schema:
            type: string
      responses:
        '200':
          description: OK
  /restaurants/{id}:
    get:
      summary: Get restaurant by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /restaurants/{id}/menu:
    get:
      summary: Get menu items
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
  /restaurants/{id}/reviews:
    get:
      summary: Get reviews
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK


